### ISSUE TITLE
Can't find pre-trained weights

### ISSUE THREAD

**Issue by amansaini25** [ManishSahu53/geospatial_unet#11]
Hi!
I find your repository interesting and tried to work on it by looking at tutorials, but the drive link mentioned in the repo. is expired. Please acknowledge if I can get any help.

**Comment by ManishSahu53** [comment]
Here is the updated link: https://drive.google.com/file/d/1e8A_Hck4AwgoDcQG5JzZRP_1gW1X_xph/view?usp=sharing
Although this is valid for 0.2.0 version
