### ISSUE TITLE
Create a clear tutorial for model training and prediction

### ISSUE THREAD

**Issue by ManishSahu53** [ManishSahu53/geospatial_unet#9]

**Comment by ManishSahu53** [comment]
Merged to Master

**Comment by amansaini25** [comment]
Can I get a glimpse of how training data looks like?(a single data point is enough)

**Comment by ManishSahu53** [comment]
Here are the sample dataset: https://www.cs.toronto.edu/~vmnih/data/

**Comment by amansaini25** [comment]
Thanks a lot for your help.
